
# -------------------------------------------------------------------------
# Build Stage 0 | Install NPM dependencies and Build assets to production
#--------------------------------------------------------------------------
FROM node:12-alpine AS stage0
WORKDIR /var/www
COPY ./src/ /var/www/

RUN rm -rf public/css && rm -rf public/js && rm -rf public/img
RUN npm install npm -g && npm install && npm run production

# ------------------------------------------------------
# Build Stage 1 | Copy Public directory to Nginx
#-------------------------------------------------------
FROM nginx:1 AS stage1
COPY ./nginx/prod/conf.d/app.prod.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www
COPY --from=stage0 /var/www/public /var/www/public
EXPOSE 80
