FROM node:12-alpine AS stage1
WORKDIR /var/www
COPY ./src/ /var/www/

RUN rm -rf public/css && rm -rf public/js && rm -rf public/img
RUN npm install npm -g
RUN npm install
RUN npm run production

FROM nginx:1
COPY ./nginx/prod/conf.d/app.prod.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www
COPY --from=stage1 /var/www/public /var/www/public
EXPOSE 80
